fisa_django_mg/blog/urls.py
from django.urls import path
from . import views

app_name='blog_app' # 어디서나 blog_app:blog 라고 작성하면 localhost:8000/blog/post-list를 가리키게 됨
urlpatterns = [
    # blog 앱 내부의 경로를 지정할 부분
    # 주소줄, 실행할 함수
    # 빈 값을 호출하면 views에 있는 index를 호출해줘
    # path('', views.index), # 없는 경로를 호출하고 있음, (localhost:8000경로, 경로를 호출하면 실행할 함수의 위치)
    
    # post-list에서 호출, PostList를 가져와서 view처럼 쓸 거야, name은 서버 안에서 개발자가 부를 절대적인 이름
    # paginate 는 한 페이지에 몇개씩 글을 출력할 것인지
    path('post-list', views.PostList.as_view(paginate_by=5), name='post_list'), 
    
    path('about-me', views.about_me, name='about_me'), # 상대경로
    path('', views.about_me, name='about_me'), # 기본페이지

    # detailview url : 동적으로 변하는 값들은 <자료형:필드명> 형태로 작성
    path('<int:pk>/', views.PostDetail.as_view()),
    path('create-post/', views.PostCreate.as_view(), name="create"),  # blog_app:create   
    # 글 작성 =/= 글 수정, update는 글번호(pk)를 통해서 이미 있는 글 수정
    path('edit-post/<int:pk>', views.PostUpdate.as_view(), name='update'),
    path('delete-post/<int:pk>', views.PostDelete.as_view(), name='delete'),

    path('user-delete/', views.user_delete, name='user_delete'), # blog_app:user_delete

    # 같은 tag를 가진 글끼리 게시판에 보여주기
    path('tag/<str:slug>', views.tag_post, name='tag'),
    
    # 댓글 조회 -> post-detail.html 안에서 동작하도록
    # 댓글 작성 - 글의 번호 blog/30/
    path('<int:pk>/create-comment/', views.create_comment, name='create_comment'),
    # 댓글 수정 - 댓글의 번호
    path('update-comment/<int:pk>', views.CommentUpdate.as_view(), name='update_comment'),
    # 댓글 삭제
    path('delete-comment/<int:pk>',  views.delete_comment, name='delete_comment'),

    # 검색을 위한 주소
    path("search/<str:q>/", views.PostSearch.as_view(), name='post_search'),

]    

fisa_django_mg/fisa_django/urls.py
from django.contrib import admin
from django.urls import path, include
# python -m pip install Pillow

# 이미지 업로드 필드를 위한 추가
from django.conf import settings
from django.conf.urls.static import static

# 디버그
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls')), # localhost:8000/blog/실제 blog/urls.py에 적힌 주소로 참고함 
    # path("account/", include('account.urls')), 아래랑 겹침
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls'))
] + debug_toolbar_urls()


# static으로 관리할거야, setting에서 media_url을 달고 오는 애들을
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fisa_django_mg/blog/models.py
from django.db import models
from django.contrib.auth.models import User # 사용자 테이블

# Create your models here.
# 하나의 테이블을 클래스 단위로 사용
# models모듈의 Model 클래스를 상속받는 자식클래스 생성
# 게시글에 필요한 필드는 무엇무엇일까요


# Tag 테이블 작성 - pk는 자동생성
class Tag(models.Model):
    tag_name = models.CharField(max_length=30, unique=True)
    
    #  slug : 짧은 라벨로서, 문자/숫자/밑줄/하이픈만을 포함함
    #  일반적으로 URL에 사용됨
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True)

    def __str__(self):
        return self.tag_name
    
    def get_absolute_url(self): 
        return f'/blog/tag/{self.slug}'    


# Post 테이블 작성
class Post(models.Model): 
    
    # CharField : 글자 수가 정해진 input 타입
    title = models.CharField(max_length=50)
    # textfield 자료형 사용
    content = models.TextField()
		
    # 작성된 시간
    # django model 이 최초 저장(insert) 시에만 현재날짜(date.today()) 를 적용
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    # auto_now_add = now()함수와 동일한 작동
    created_at = models.DateTimeField(auto_now_add=True) 
    
    # 수정된 시간
    # django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 


    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    # blank=True - 필수 항목 아님이라는 파라메터


    # 외래키와 프라이머리키의 관계
    # cascade - user가 삭제되면 관련있는 post 테이블의 모든 글이 삭제
    # set null - user가 삭제되면 관련있는 post 테이블의 모든 글에 author 항목은
    # forign키로 user 테이블의 pk 참조
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    # 다대다 관계 설정
    tag = models.ManyToManyField(Tag)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    # 번호와 글 제목 반환
    def __str__(self):
        return f'[[{self.pk}] {self.title}]'
		
    def get_absolute_url(self): 
        return f'/blog/{self.pk}'

    def get_file_extension(self):
        return f'{self.file_upload}'.split('.')[-1]
    

    # post-list와 상세페이지 연결
    # 글/더보기를 클릭하면 blog/pk로 연결
    # 모델의 행/데이터에서는 함수를 사용할 수 있어
    # 클래스 객체에서는 모두 사용 가능
    def get_absolute_url(self): 
        return f'/blog/{self.pk}'


# Comment 테이블 : 글이 있어야 댓글이 가능 -> post 테이블 아래 위치
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # 하나의 포스트에 여러개의 댓글이 달릴 수 있음

    author = models.ForeignKey(User, on_delete=models.CASCADE) # 여러 사람이 댓글을 작성할 수 있음

    content = models.TextField()

    # 작성된 시간
    # django model 이 최초 저장(insert) 시에만 현재날짜(date.today()) 를 적용
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    # auto_now_add = now()함수와 동일한 작동
    created_at = models.DateTimeField(auto_now_add=True) 
    
    # 수정된 시간
    # django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 
      
    def __str__(self):
        return f'[[{self.pk}] {self.content}]'
    
    def get_absolute_url(self): 
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'  # #은 html에서 ID가 됨

fisa_django_mg/blog/forms.py
from .models import Comment
from django import forms
# 게시글 폼

# 커스텀한 폼을 사용하기 위한 클래스
class CommentForm(forms.ModelForm):
    class Meta: # 추가적인 정보들을 달아서 보낼 때 사용하는 클래스
        model = Comment
        fields = ['content']

fisa_django_mg/blog/views.py
from typing import Any
from django.db.models.query import QuerySet, Q
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render, redirect
from .models import Post, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify
from .forms import CommentForm

# 회원탈퇴
from django.views.decorators.http import require_POST # POST 방식으로만 접근해야하는 함수 앞에 적어줌
from django.contrib.auth import logout as auth_logout #logout 담당 함수
from django.contrib.auth.decorators import login_required # 인증을 확인해서 로그인 상태에서만 접근할 수 있게 허가하는 데코레이터
from django.contrib.auth import authenticate, login # authenticate : 인가, login : 인증 담당
from django.core.exceptions import PermissionDenied  #인가 - 권한이 없으면 예외...
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages  # 예외나 상황에 대한 메시지 처리 

# 글수정/삭제
# from myapp.models import Author

# Mixin이라는 부가 기능들을 확인하기 위해 다중상속으로 주 기능을 확장하는 별도의 클래스
# 주기능을 가진 클래스보다 앞에 작성해줍니다. 
# Mixin은 상속이라기 보다는 포함, 확장이라는 개념으로 생각할 수 있다.
# 장고의 Mixin
# user의 정보로 필드로 달아서 보내면 변조의 가능성이 있기 때문에 view 단에서 처리합니다.
class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content", "head_image","file_upload"]

    # CreateView가 내장한 함수 - 오버라이딩 
    # tag는 참조관계이므로 Tag 테이블에 등록된 태그만 쓸 수 있는 상황
    # 임의로 방문자가 form에 Tag를 달아서 보내도록 form_valid()에 결과를 임시로 담아두고
    # 저장된 포스트로 돌아오도록 
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_active):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()   # 책; 독후감, 작가명

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(tag_name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tag.add(tag)

            return response

        else:
                return redirect('/blog/')


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload']
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403
    
    # 이미 있는 글을 불러와서 원본에서 수정한 내용을 변경
    # author 필드는 당연히 이전에 글을 생성한 작성자로 채워져있고, 
    # LoginRequiredMixin으로 로그인한 유저 확인하므로 form_valid는 오버라이딩하지 않음
    # 태그에 여러개 보내면 겹치지 않는 것만 새로 성성하는 기능은 필요하므로 get_context_data를 오버라이딩
    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tag.exists():
            tags_str_list = list()
            for t in self.object.tag.all():
                tags_str_list.append(t.tag_name)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context

    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 
    # 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tag.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(tag_name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tag.add(tag)

        return response
        
class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post 
    success_url = '/blog/'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return redirect(success_url)
        else:
            raise PermissionDenied


class PostList(ListView):   # post_list.html, post-list
    model = Post 
    # template_name = 'blog/index.html' 
    ordering = '-pk' 
    context_object_name = 'post_list'

class PostSearch(PostList):
    paginate_by=5
    def get_queryset(self):
        q = self.kwargs['q'] # 검색어가 q라는 변수에 저장됨
        # Q로 전문검색으로 만들기, 단순히 제목만 검색은 filter(title__contains)
        post_list = Post.objects.filter(Q(title__contains=q) | Q(content__contains=q) | Q(tag__tag_name__contains=q)).select_related('author') 
        return post_list
    
# Create your views here.
def index(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    posts = Post.objects.all()
    return render(
        request,
        'blog/index.html',{
            'posts':posts, 'my_list': ["apple", "banana", "cherry"], 'my_text': "첫번째 줄 \n 두번째 줄", 'content' : '<img src="고양이.jpg"/>',
        } # 없는 index.html을 호출하고 있음
    )

def about_me(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    return render(
        request,
        'blog/about_me.html'
    )

class PostDetail(DetailView):
    model = Post 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = '임의로 작성한 새로운 변수'
        context["comment_form"] = CommentForm
        print(context["now"] )
        return context
    
@login_required
def user_delete(request):
    # 로그인 상태 확인
    if request.user.is_authenticated:
        # user_delete()호출
        request.user.delete()
        
        # 로그아웃
        auth_logout(request) #세션 지우기
        # 원래 페이지로 로그인 안된 상태로 원상복귀
        return redirect('blog_app:about_me')

# 같은 tag(slug)를 가진 글끼리 출력하기
# path('tag/<str:slug>' , views.tag_posts, name='tag') 에서 이어짐
# url로 전달받은 slug를 아규먼트로 사용하게 됨
def tag_post(request, slug):
    # tag가 없는 경우 : 
    if slug == "no-tag":
        posts = Post.objects.filter(tag=None)
    # tag가 있는 경우
    else:
        # slug파라미터가 일치하는 값들을 가져옴
        # tag를 포함한 object를 추려냄
        tag = Tag.objects.get(slug=slug)
        # object를 post로 넘겨줘서 사용
        # posts = Post.objects.filter(tag=tag)
        # .select_related : 쿼리 최적화, foreignkey나 일대일관계로 연결된 테이블의 데이터를 미리 가져오는 메서드, 
        # 데이터를 한 번에 저장해놓고 필요할 때 가져다 씀
        posts = Post.objects.filter(tag=tag).select_related('author') 
    return render(request, 'blog/post_list.html', {'post_list':posts})  # 템플릿 재사용


 # 댓글 작성 - 글의 번호 blog/30/
def create_comment(request, pk):
    # GET / POST 서로 다른 결과 return 
    # 로그인 상태 확인 
    if request.user.is_authenticated:
        post = Post.objects.get(pk=pk)

        # POST 리턴 -> Comment 테이블에 값 업데이트
        if request.method == 'POST':
            comment_form = CommentForm(request.POST) # 작성한 content 
            if comment_form.is_valid():
                comment = comment_form.save(commit=False) # 객체는 만들었으나 아직 DB에 반영하지 않은 상태
                comment.post = post # 임시 저장상태로 field로 입력받지 않은 값들을 추가
                comment.author = request.user  # 임시 저장상태로 field로 입력받지 않은 값들을 추가
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied
    # GET 리

# 댓글 수정 - 댓글의 번호
# comment_form.html 
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403


def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk) # comment 객체 가져옴
    post = comment.post

    # 로그인 된 상태이고, comment.author 이면 
    if request.user.is_authenticated and request.user == comment.author:
            comment.delete()
            return redirect(post.get_absolute_url())  # /blog/32
    else:
        raise PermissionDenied

fisa_django_mg/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About 김연지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        /* The navigation bar */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: fixed; /* Set the navbar to fixed position */
            top: 0; /* Position the navbar at the top of the page */
            width: 100%; /* Full width */
            }

    </style>
</head>
<body>

<!-- Header-->
<div id="header" class="py-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container px-5">
            <a class="navbar-brand">YEONJI KIM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:about_me' %}">About me</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:post_list' %}">blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="#three">Technical Editor</a></li>             
                </ul>

                {% if user.is_authenticated %}   
                {# 로그인 상태이면 #}
                    {# 본인 ID #}
                    <span class="text-secondary fw-bold"> <a href="{% url 'account_change_password' %}">{{ user.username }} </a> </span>&nbsp;
                    {# 로그아웃 버튼 #}
                    <a class="btn btn-secondary" href="{% url 'account_logout' %}" role="button">로그아웃</a>&nbsp;&nbsp;
                    {# 회원탈퇴 버튼 #}
                    <a class="btn btn-secondary" href="{% url 'blog_app:user_delete' %}" role="button">회원탈퇴</a>&nbsp;&nbsp;

                    {% else %}
                {# 로그아웃 상태이면 #}
                {# 로그인 버튼 #}
                <a class="btn btn-secondary" href="{% url 'account_login' %}" role="button">로그인</a>&nbsp;&nbsp;
                {# 회원 가입 버튼 #}
                <a class="btn btn-secondary" href="{% url 'account_signup' %}" role="button">회원가입</a>&nbsp;&nbsp;
            {% endif %}
            </div>
        </div>
    </nav>
</div>

{% block page_area %}

{% endblock %}

<!-- Footer-->
<div id="footer" class="bg-dark py-4 mt-auto fixed-bottom">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; YEONJIKIM 2024</div></div>
            <div class="col-auto">
                <span class="text-white mx-1">atangi@naver.com</span>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="mailto:atangi@naver.com">Contact</a>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</body>
</html>

fisa_django_mg/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_area %}
{% load crispy_forms_tags %}

<!-- {# % if user.is_authenticated and user.username == post.author % #} 수정/삭제 없음-->
{% if user.is_authenticated and user == post.author %}
    <a class="btn btn-secondary" href="/blog/edit-post/{{post.pk}}" role="button">수정</a>&nbsp;&nbsp;          
    {# <!-- <a class="btn btn-secondary" href="/blog/delete-post/{{post.pk}}" role="button">삭제</a>&nbsp;&nbsp;           -->#}
          <!-- Button to open the modal -->
          <a class="btn btn-danger" href="#" role="button" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</a>&nbsp;&nbsp;

          <!-- The Modal -->
          <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel">삭제 확인</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                          정말 삭제하시겠습니까?
                      </div>
                      <div class="modal-footer">
                          <form method="POST" action="{% url 'blog_app:delete' post.id %}">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">예</button>
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">아니오</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
                  {% endif %}

                            <!-- Post content-->
                            <article>
                                <!-- Post header-->
                                <header class="mb-4">
                                    <!-- Post title-->
                                    <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                                    <!-- Post meta content-->
                                    <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
                                    <!-- Post categories tag가 있는 글이면 해당 tag가 보여지도록 반복문으로 출력하기. tag_name으로-->
                                    <!-- all쓰면 모두 꺼내짐 -->
                                    {% if post.tag.exists %}
                                    {% for tag in post.tag.all %}                                    
                                        <a class="badge bg-secondary text-decoration-none link-light" href="{{tag.get_absolute_url}}">{{tag.tag_name}} {{tag.post_set.count}}</a>
                                    {% endfor %}
                                    {% endif %}
                                </header>
                                <!-- Preview image figure-->
                                {% if post.header_img %}
                                <figure class="mb-4">
                                    <img class="img-fluid rounded" src="{{ post.header_img.url }}" alt="..." /></figure>
                                {% endif %}
                                    <!-- Post content-->
                                <section class="mb-5">
                                    <p class="fs-5 mb-4"> {{ post.content }}</p>
                                    {% if post.file_upload %}
                                    <a href="{{ post.file_upload.url }}" class="btn btn-dark">다운로드</a>
                                    {% endif %}
                                </section>

                                <!-- Comment Form과 Comment CRUD를 사용하기 위한 항목 -->
                                <section>
                                    <div class="card bg-light"> 
                                        <div class="card-body" id="comment-area">
                                        <!-- Comments Form -->
                                        <div class="card my-4">
                                            <h5 class="card-header">댓글</h5>
                                            <div class="card-body">
                                                {% if user.is_authenticated %}
                                                    <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}/create-comment/">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            {{ comment_form | crispy }}
                                                        </div>
                                                        <button type="submit" class="btn btn-dark">등록</button>
                                                    </form>
                                                {% else %}
                                                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Log in and leave a comment</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                
                                        {% if post.comment_set.exists %}
                                            {% for comment in post.comment_set.iterator %}
                                                <!-- Single Comment -->
                                                <div class="d-flex align-items-center" id="comment-{{ comment.pk }}">
                                                    <div class="flex-grow-1 ms-3">
                                                        {% if user.is_authenticated and comment.author == user %}
                                                            <div class="float-right">
                                                                <a role="button"
                                                                   class="btn btn-sm btn-secondary"
                                                                   id="comment-{{ comment.pk }}-update-btn"
                                                                   href="/blog/update-comment/{{ comment.pk }}">
                                                                    수정
                                                                </a>
                                                                <a role="button"
                                                                   href="#"
                                                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                                                   class="btn btn-sm btn-danger"
                                                                   data-bs-toggle="modal" data-bs-target="#deleteCommentModal-{{ comment.pk }}">
                                                                    삭제
                                                                </a>
                                                            </div>
                                
                                                            <!-- Modal -->
                                                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                                                <div class="modal-dialog" role="document">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title" id="deleteCommentModalLabel">정말 삭제하나요?</h5>
                                                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                                                <span aria-hidden="true">&times;</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body">
                                                                            <del>{{ comment | linebreaks }}</del>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                                                                            <a role="button" class="btn btn-danger" href="/blog/delete-comment/{{ comment.pk }}">삭제</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                
                                                        {% endif %}
                                                        <h5 class="mt-0">
                                                            {{ comment.author.username }}
                                                            &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                                                        </h5>
                                                        <p>{{ comment.content | linebreaks }}</p>
                                                        {% if comment.created_at != comment.updated_at %}
                                                            <p class="text-muted float-right"><small>Updated: {{ comment.updated_at }}</small></p>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </section>
                            </article>

{% endblock %}